export const ADD_COUNTRY = 'ADD_COUNTRY';
export const REMOVE_COUNTRY = 'REMOVE_COUNTRY';
export const SEARCH_COUNTRY = 'SEARCH_COUNTRY';
export const SORT_COUNTRIES = 'SORT_COUNTRIES';

export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_COUNTRIES_SUCCEEDED = 'FETCH_COUNTRIES_SUCCEEDED';
export const FETCH_COUNTRIES_FAILED = 'FETCH_COUNTRIES_FAILED';
